compiler = g++
SOURCES=main.cpp \
			E:/programare_2023-2024/familia_c/c++/matrice/matrix.cpp
INCLUDE=-IE:/programare_2023-2024/familia_c/c++/matrice
all:
	$(compiler) $(SOURCES) $(INCLUDE)
clean:
	rm *.exe