name: Schedule test
on:
    push :
    schedule:
    - cron: "*/1 * * * *"
    # This shall run every minute
jobs:
  schedule_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Access local repo
        run: |
          echo "Accessing local repo"
          ls -la
          pwd