name: Acces repo test
on:
    push :
    #schedule:
    # - cron: "* 1 * * *"
    # This shall run every hour
    # See https://crontab.guru/
jobs:
  acces:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Access local repo
        run: |
          echo "Accessing local repo"
          date
          ls -la
          pwd
          py python/test.py